#!/bin/sh

cmd="$1"
if [ -z "$cmd" ]
then
  printf 'Usage: %s COMMAND FILE [FILE]*\n' $0 >&2
  echo "  Run COMMAND when any of the files change." >&2
  exit 1
fi
shift

oldkey=""
while true
do
  newkey=`ls --full-time "$@"`
  if [ "$newkey" == "$oldkey" ]
  then
    sleep 1s
  else
    sleep .5s  # Try to avoid race conditions from slow writes.
    printf '\033]0;RUNNING\a'
    printf '\n\n\n\n\n\n\n\n\n\n' >&2
    printf 'Running: sh -c "%s"\n' "$cmd" >&2
    oldkey=`ls --full-time "$@"`

    sh -c "$cmd" < /dev/null
    statuscode=$?
    printf 'Result was: %d\n' "$statuscode" >&2
    if [ "$statuscode" = 0 ]
    then
      printf '\033]0;PASS %d\a' "$statuscode"
    else
      printf '\033]0;FAIL %d\a' "$statuscode"
    fi
  fi
  sleep 1
done

